### ISSUE TITLE
是否无法加载启用trt加速的engine权重

### ISSUE THREAD

**Issue by unicorn5514** [zzojbk/Apex-#1]

**Comment by unicorn5514** [comment]
或者是我加载用yolov5n训练的模型也会报错F:\py3.8\python.exe F:\aim\Apex--main\Apex_YOLOv5-main\Apex_YOLOv5-main\apex.py 
Traceback (most recent call last):
  File "F:\aim\Apex--main\Apex_YOLOv5-main\Apex_YOLOv5-main\apex.py", line 65, in <module>
    model = load_model(args)
  File "F:\aim\Apex--main\Apex_YOLOv5-main\Apex_YOLOv5-main\aim\cs_model.py", line 8, in load_model
    model = attempt_load(args.model_path, map_location=device)  # load FP32 model
  File "F:\aim\Apex--main\Apex_YOLOv5-main\Apex_YOLOv5-main\models\experimental.py", line 92, in attempt_load
    ckpt = torch.load(attempt_download(w), map_location=map_location)  # load
  File "F:\py3.8\lib\site-packages\torch\serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "F:\py3.8\lib\site-packages\torch\serialization.py", line 1172, in _load
    result = unpickler.load()
  File "F:\py3.8\lib\site-packages\torch\serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'DetectionModel' on <module 'models.yolo' from 'F:\\aim\\Apex--main\\Apex_YOLOv5-main\\Apex_YOLOv5-main\\models\\yolo.py'>
